project:
  type: website
  output-dir: docs
  
website:
  search: false
  page-footer: 
    center: "© 2025 Samantha Mapleton - Text written by a human (not a Bot) using [Quarto](https://quarto.org)"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
    right:
      - href: About this Project.qmd
        text: About
      - href: Study Area.qmd
        text: Study Area
        icon: 1-circle-fill
      - href: Academic Research at Petra.qmd
        text: History of Research
        icon: 2-circle-fill
      - href: Gallery.qmd
        text: Image Gallery
        icon: 3-circle-fill
      - href: Reflective Essay.qmd
        text: Reflective Essay
        icon: 4-circle-fill

format:
  html:
    page-layout: full
    theme: lux
    fontsize: 18px
    css: styles.css
    
editor: visual
